language: node_js
node_js:
  - "4.4.2"
  - "5.0.0"
  - "6.9.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm set progress=false
install: npm install
script: npm run test
notifications:
  slack: wfp:70WNjvrfKXDIMHgzKfjMtsEx
